update for MacOS

diff --git a/src/main/bash/bin/make-cpan-dist.in b/src/main/bash/bin/make-cpan-dist.in
--- a/src/main/bash/bin/make-cpan-dist.in
+++ b/src/main/bash/bin/make-cpan-dist.in
@@ -16,6 +16,7 @@ Options
 -b buildspec   - use a buildspec file instead of options
 -d description - description to be included CPAN
 -D file        - use file as the dependency list
+-T file        - use file as the test dependency list
 -e path        - path for extra .pl files to package
 -h             - help
 -f file        - file containing a list of extra files to include
@@ -33,7 +34,7 @@ Options
 
 NOCLEANUP=1, PRESERVE_MAKEFILE=1 can also be passed as environment variables.
 
-Copyright (c) 2019 Robert C. Lauer, All rights reserved.
+Copyright (c) 2022 Robert C. Lauer, All rights reserved.
 This is free software and may be used for any purpose without charge.
 EOT
     
@@ -69,10 +70,10 @@ function cleanup {
     test -n "$tmp_gitdir" && rm -rf "$tmp_gitdir"
     test -n "$package_files" && rm "$package_files"
     test -n "$exe_files" && rm "$exe_files"
-    
+
     if test -n "$workdir"; then
-        for a in requires test-requires provides; do
-            rm -f ${workdir}/$a ${workdir}/$a.tmp
+        for a in *.tmp; do
+            rm -f ${workdir}/$a
         done
     fi
 
@@ -84,8 +85,8 @@ function perl_requires {
     if test -n "@PERL_REQUIRES@"; then
         /usr/lib/rpm/perl.req "$1" | perl -npe 's/^perl\((.*)\)/$1/'
     else
-        echo "no /usr/lib/rpm/perl.req found!"
-        echo "Install rpm-build package or use the -r option to provide your own dependency checker"
+        >&2 echo "ERROR: no /usr/lib/rpm/perl.req found!"
+        >&2 echo "Install rpm-build package or use the -r option to provide your own dependency checker"
         exit 1;
     fi
 }
@@ -98,14 +99,28 @@ function get_module_versions {
         echo "file $infile not found!"
         return;
     fi
+
+    modules=$(mktemp)
     
-    for a in $(sort -u "$infile" | perl -npe 's/^perl\((.*)\)$/$1/;'); do
-        if test -n "$ANY_VERSION"; then
-            echo "$a 0"
-        elif test -n "$a"; then
-            @perlenv@ -I ${perl5libdir} -M$a -e 'print "'$a'"," ", $'$a'::VERSION,"\n";' 2>/dev/null || echo "$a 0" || true;
-        fi
-    done
+    sort -u "$infile" | perl -npe 's/^perl\(//; s/\)\s*$//;' >$modules;
+
+    while read -r a; do 
+	module="$(echo "$a" | awk '{print $1}')"
+	version="$(echo "$a" | awk '{print $2}')"
+	
+	if test -n "$ANY_VERSION"; then
+	    echo "$module 0"
+	elif test -n "$a" && ! test -n "$version"; then
+	    @perlenv@ -I ${perl5libdir} \
+	     -M$a \
+	     -e 'print "'$module'"," ", $'$module'::VERSION,"\n";' || echo "$module 0" || true;
+	else
+	    echo "$module $version";
+	fi
+        
+    done <$modules
+
+    rm $modules
 }
 
 function scan() {
@@ -113,13 +128,13 @@ function scan() {
     
     if [ "$PERL_REQUIRES" = "SCANDEPS" ]; then
         if test -z "@scandeps@"; then
-            echo "no scandeps.pl found!"
+            >&2 echo "no scandeps.pl found!"
             exit 1
         else
             set -o pipefail
-            echo "Scanning $scan_target..."
+            >&2 echo "Scanning $scan_target..."
             if ! @scandeps@ -R $scan_target | perl -npe "s/^\'(.*?)\'.*\$/\$1/;" >>${workdir}/requires.tmp; then
-                echo "ERROR: could not resolve dependencies for $scan_target"
+                >&2 echo "ERROR: could not resolve dependencies for $scan_target"
                 exit 1;
             else
                 if test -n "$DEBUG"; then
@@ -136,129 +151,103 @@ function scan() {
 # | SCRIPT STARTS HERE |
 # +--------------------+
 
-OPTS=$(getopt -o Ab:D:e:sphg:t:a:m:d:r:l:o:vxf:R:P:z -- "$@")
+while getopts "h?Ab:D:e:spg:t:a:m:d:r:l:o:vxf:R:P:zT:" arg "$@"; do
+    
+    case "${arg}" in
 
-if [ $? -ne 0 ]; then
-    echo "could not parse options"
-    exit $?
-fi
-
-eval set -- "$OPTS"
-
-set -e
-
-while [ $# -gt 0 ]; do
-    case "$1" in
-        -A)
-            ANY_VERSION="$1";
-            shift;
+        A)
+            ANY_VERSION="1";
             ;;
-        -e)
-            perl5bindir="$2";
-            shift;
-            shift;
+        e)
+            perl5bindir="$OPTARG";
             ;;
         
-        -z)
+        z)
             DRYRUN="--dryrun";
             shift;
             ;;
         
-        -b) BUILDSPEC="$2";
-            shift;
-            shift;
+        b) BUILDSPEC="$OPTARG";
+           ;;
+        
+        D)
+            dependency_file="$OPTARG";
             ;;
-        -D)
-            dependency_file="$2";
-            shift;
-            shift;
+
+        T)
+            test_dependency_file="$OPTARG";
             ;;
         
-        -s)
+        s)
             PERL_REQUIRES="SCANDEPS"
-            shift;
             ;;
-        -R)
-            recurse_directories="$2";
-            shift;
-            shift;
+
+        R)
+            recurse_directories="$OPTARG";
             ;;
-        -P)
-            provides="$2";
+
+        P)
+            provides="$OPTARG";
             test -n "$provides" && recurse_directories="no"
-            shift;
-            shift;
+
             ;;
-        -f)
-            EXTRA="$2";
-            shift;
-            shift;
+        f)
+            EXTRA="$OPTARG";
             ;;
-        -x)
-            NOCLEANUP="$1";
-            shift;
+
+        x)
+            NOCLEANUP="1";
             ;;
-        -p)
-            PRESERVE_MAKEFILE="$1";
-            shift;
+
+        p)
+            PRESERVE_MAKEFILE="1";
             ;;
-        -v)
-            VERBOSE="$1";
-            shift;
+
+        v)
+            VERBOSE="1";
             ;;
-        -o)
-            destdir="$2";
-            shift;
-            shift;
+
+        o)
+            destdir="$OPTARG";
             ;;
-        -a)
-            author="$2";
-            shift;
-            shift;
+
+        a)
+            author="$OPTARG";
             ;;
-	-h)
+
+        h)
 	    usage;
 	    ;;
-        -m)
-            module="$2";
-            shift;
-            shift;
+
+        m)
+            module="$OPTARG";
             ;;
-        -d)
-            description="$2";
-            shift;
-            shift;
+
+        d)
+            description="$OPTARG";
             ;;
-        -g)
-            git_project="$2";
-            shift;
-            shift;
+
+        g)
+            git_project="$OPTARG";
             ;;
-        -l)
-            perl5libdir="$2";
-            shift;
-            shift;
+
+        l)
+            perl5libdir="$OPTARG";
             ;;
-        -r)
-            PERL_REQUIRES="$2";
-            shift;
-            shift;
+
+        r)
+            PERL_REQUIRES="$OPTARG";
             ;;
-        -t)
-            testsdir="$2";
-            shift;
-            shift;
+
+        t)
+            testsdir="$OPTARG";
             ;;
-	--)
-	    break;
-	    ;;
-	*)
-	    break;
-	    ;;
     esac
 done
 
-shift;
+test -n "$DEBUG" && set -x
+
+shift $((OPTIND -1))
 
 if test -n "$BUILDSPEC"; then
     PROJECT_HOME=$PROJECT_HOME @libexecdir@/make-cpan-dist.pl \
@@ -342,7 +331,7 @@ if [ "$recurse_directories" = "yes" ]; then
 else
     if test -n "$provides"; then
         if test -s "$provides"; then
-            echo "$module.pm" >> $provides
+            echo "$module.pm" >>$provides
             for a in $(cat $provides) "$module.pm"; do
                 echo "${PROJECT_HOME}/${perl5libdir}/$a" >> $package_files
             done
@@ -356,21 +345,30 @@ else
     fi
 fi
 
+for a in $(cat $package_files | sort -u); do
+    required_module=${a##${PROJECT_HOME}/${perl5libdir}/}
+    echo $required_module >> ${workdir}/provides.tmp
+    mkdir -p $(dirname ${builddir}/lib/$required_module)
+    cp $a ${builddir}/lib/$required_module
+done
+    
+if test -s "$exe_files"; then
+    mkdir -p ${builddir}/bin
+    
+    for a in $(cat $exe_files); do
+        cp $a ${builddir}/bin
+    done
+fi
+
 if test -z "$dependency_file"; then
+
     for a in $(cat $package_files | sort -u); do
-        required_module=${a##${PROJECT_HOME}/${perl5libdir}/}
-        echo $required_module >> ${workdir}/provides.tmp
-        mkdir -p $(dirname ${builddir}/lib/$required_module)
-        cp $a ${builddir}/lib/$required_module
         scan $a;
     done
     
     # find dependencies for .pl files
     if test -s "$exe_files"; then
-        mkdir -p ${builddir}/bin
-        
         for a in $(cat $exe_files); do
-            cp $a ${builddir}/bin
             scan $a;
         done
     fi
@@ -391,35 +389,43 @@ if ! test -s ${workdir}/requires.tmp; then
     touch ${workdir}/requires.tmp
 fi
 
-cat ${workdir}/provides.tmp | perl -npe 's/\//::/g; s/\.pm$//;' | sort > ${workdir}/provides
+cat ${workdir}/provides.tmp | perl -npe 's/\//::/g; s/\.pm$//;' | sort -u > ${workdir}/provides
 sort -u ${workdir}/requires.tmp > ${workdir}/requires
 
 # remove provided files from required list
 comm -23 ${workdir}/requires ${workdir}/provides > ${workdir}/requires.tmp
 
 # get the module versions we are currently using
-get_module_versions ${workdir}/requires.tmp > ${workdir}/requires
 
-if test -n "$testsdir"; then
-    if test -d "$testsdir"; then
-        testsfile=$(mktemp);
-        ls -1 ${testsdir}/*.t >$testsfile 2>/dev/null || true
-        if test -s "$testsfile"; then
-            mkdir ${builddir}/t
-        
-            for a in $(cat $testsfile); do
-                cp $PROJECT_HOME/$a ${builddir}/t/
-                $PERL_REQUIRES $PROJECT_HOME/$a >> ${workdir}/test-requires.tmp
-            done
-            
-            # remove provided files from required list
-            sort -u ${workdir}/test-requires.tmp > ${workdir}/test-requires
-            comm -23 ${workdir}/test-requires  ${workdir}/provides > ${workdir}/test-requires.tmp
-            
-            get_module_versions test-requires.tmp > ${workdir}/test-requires
-        else
-            rm -f "$testsfile";
-            testsfile="";
+if test -z "$dependency_file"; then
+    get_module_versions ${workdir}/requires.tmp > ${workdir}/requires
+fi
+
+if test -n "$test_dependency_file"; then
+    cp $test_dependency_file ${workdir}/test-requires.tmp
+    cp ${workdir}/test-requires.tmp {workdir}/test-requires
+else
+    if test -n "$testsdir"; then
+        if test -d "$testsdir"; then
+            testsfile=$(mktemp);
+            ls -1 ${testsdir}/*.t >$testsfile 2>/dev/null || true
+            if test -s "$testsfile"; then
+                mkdir ${builddir}/t
+                
+                for a in $(cat $testsfile); do
+                    cp $PROJECT_HOME/$a ${builddir}/t/
+                    scan $PROJECT_HOME/$a >> ${workdir}/test-requires.tmp
+                done
+                
+                # remove provided files from required lis`t
+                sort -u ${workdir}/test-requires.tmp > ${workdir}/test-requires
+                comm -23 ${workdir}/test-requires  ${workdir}/provides > ${workdir}/test-requires.tmp
+                
+                get_module_versions test-requires.tmp > ${workdir}/test-requires
+            else
+                rm -f "$testsfile";
+                testsfile="";
+            fi
         fi
     fi
 fi
